export const GET__INSTRUCTOR__SPACES__REQUEST =
	'GET__INSTRUCTOR__SPACES__REQUEST'
export const GET__INSTRUCTOR__SPACES__SUCCESS =
	'GET__INSTRUCTOR__SPACES__SUCCESS'
export const GET__INSTRUCTOR__SPACES__FAIL = 'GET__INSTRUCTOR__SPACES__FAIL'
export const GET__INSTRUCTOR__SPACES__RESET = 'GET__INSTRUCTOR__SPACES__RESET'

export const POST__INSTRUCTOR__CREATE__REQUEST =
	'POST__INSTRUCTOR__CREATE__REQUEST'
export const POST__INSTRUCTOR__CREATE__SUCCESS =
	'POST__INSTRUCTOR__CREATE__SUCCESS'
export const POST__INSTRUCTOR__CREATE__FAIL = 'POST__INSTRUCTOR__CREATE__FAIL'
export const POST__INSTRUCTOR__CREATE__RESET = 'POST__INSTRUCTOR__CREATE__RESET'
