export const GET__STUDENT__SPACES__REQUEST = 'GET__STUDENT__SPACES__REQUEST'
export const GET__STUDENT__SPACES__SUCCESS = 'GET__STUDENT__SPACES__SUCCESS'
export const GET__STUDENT__SPACES__FAIL = 'GET__STUDENT__SPACES__FAIL'
export const GET__STUDENT__SPACES__RESET = 'GET__STUDENT__SPACES__RESET'

export const POST__STUDENT__JOIN__REQUEST = 'POST__STUDENT__JOIN__REQUEST'
export const POST__STUDENT__JOIN__SUCCESS = 'POST__STUDENT__JOIN__SUCCESS'
export const POST__STUDENT__JOIN__FAIL = 'POST__STUDENT__JOIN__FAIL'
export const POST__STUDENT__JOIN__RESET = 'POST__STUDENT__JOIN__RESET'
