export const GET__USER__PROFILE__REQUEST = 'GET__USER__PROFILE__REQUEST'
export const GET__USER__PROFILE__SUCCESS = 'GET__USER__PROFILE__SUCCESS'
export const GET__USER__PROFILE__FAIL = 'GET__USER__PROFILE__FAIL'
export const GET__USER__PROFILE__RESET = 'GET__USER__PROFILE__RESET'

export const PATCH__USER__PROFILE__REQUEST = 'PATCH__USER__PROFILE__REQUEST'
export const PATCH__USER__PROFILE__SUCCESS = 'PATCH__USER__PROFILE__SUCCESS'
export const PATCH__USER__PROFILE__FAIL = 'PATCH__USER__PROFILE__FAIL'
export const PATCH__USER__PROFILE__RESET = 'PATCH__USER__PROFILE__RESET'

export const PATCH__USER__PROFILE__PICTURE__REQUEST =
	'PATCH__USER__PROFILE__PICTURE__REQUEST'
export const PATCH__USER__PROFILE__PICTURE__SUCCESS =
	'PATCH__USER__PROFILE__PICTURE__SUCCESS'
export const PATCH__USER__PROFILE__PICTURE__FAIL =
	'PATCH__USER__PROFILE__PICTURE__FAIL'
export const PATCH__USER__PROFILE__PICTURE__RESET =
	'PATCH__USER__PROFILE__PICTURE__RESET'
